# Generated by Django 4.2.3 on 2023-07-07 13:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('geolocalizacao', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
