# Generated by Django 4.2.3 on 2023-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_geolocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='geolocalizacao',
            new_name='geolocation_data',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='data_hora',
            new_name='occurrence_datetime',
        ),
        migrations.RenameField(
            model_name='geolocation',
            old_name='usuario',
            new_name='user',
        ),
    ]
